remote_theme: pages-themes/modernist@v0.2.0
title: Squid configuration manual
description: "Reference manual for squid's configuraiton directives"

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jemoji

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: :path/:basename # make sitemap.xml not include .html
